### ISSUE TITLE
Support napi (Node API)

### ISSUE THREAD

**Issue by hvlxh** [AllayBE/AllayBE#4]
Support to use node in c++ through node c++ addon api

https://nodejs.org/dist/latest-v18.x/docs/api/addons.html
https://nodejs.org/dist/latest-v18.x/docs/api/n-api.html

**Comment by vp817** [comment]
this is not even complete and i didnt touch it for weeks

**Comment by vp817** [comment]
and i dont think i will touch node for anything other than for plugins but that is not something that has been decided since i was thinking of only using lua for plugins support

**Comment by hvlxh** [comment]
I will open an pr for cleanups and of course, i will contribute if decided to use node api

**Comment by vp817** [comment]
ok
